name: workaround
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  animations: ^2.0.11
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.4
  collection: ^1.18.0
  cronet_http: ^1.2.0
  dartfield: ^1.1.0
  dotted_border: ^2.1.0
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_location_marker: ^8.0.8
  flutter_map_marker_cluster: ^1.3.5
  formz: ^0.7.0
  fpdart: ^1.1.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.0
  intl: ^0.18.1
  jiffy: ^6.2.1
  latlong2: ^0.9.1
  location_client:
    path: packages/location_client
  morphable_shape: ^1.6.6
  profile_repository:
    path: packages/profile_repository
  random_avatar: ^0.0.8
  shape_maker: ^0.0.3
  shared_kernel:
    path: packages/shared_kernel
  skeletonizer: ^1.1.2+1
  stream_transform: ^2.1.0
  supabase_flutter: ^2.5.2
  url_launcher: ^6.2.6
  user_repository:
    path: packages/user_repository
  very_good_infinite_list: ^0.7.1
  work_application_repository:
    path: packages/work_application_repository
  work_repository:
    path: packages/work_repository

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/images/illustration_balloon.png
    - assets/images/illustration_sally.png
    - assets/images/icon_google.png
  uses-material-design: true
  generate: true

dart_define:
  variables:
    - name: SUPABASE_URL
      description: Supabase API URL
      required: true
    - name: SUPABASE_ANON_KEY
      description: Supabase API key
      required: true
    - name: GOOGLE_OAUTH_WEB_CLIENT_ID
      description: Google OAuth web client ID
      required: true
    - name: GOOGLE_OAUTH_IOS_CLIENT_ID
      description: Google OAuth iOS client ID
      required: true
    - name: ANDROID_GOOGLE_API_KEY
      description: Google API key for Android
      required: true
    - name: GOONG_API_KEY
      description: Goong API key
      required: true
    - name: MAPTILER_API_KEY
      description: Maptiler API key
      required: true
  flavors:
    - name: production
      description: The production flavor
    - name: staging
      description: The staging flavor
    - name: development
      description: The development flavor
