name: authentication_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  very_good_analysis: ^5.1.0
dependencies:
  fpdart: ^1.1.0
  google_sign_in: ^6.2.1
  shared_kernel:
    path: ../shared_kernel
  supabase_flutter: ^2.3.4
