name: infrastructure
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  very_good_analysis: ^5.1.0
dependencies:
  equatable: ^2.0.5
  supabase_flutter: ^2.3.4
