// This file was generated by package:dart_define, DO NOT modify or remove these comments
class DartDefine {
  DartDefine._();
  
  /// The flavor the app was launched with
  static Flavor get flavor => FlavorExtension.fromString(
        const String.fromEnvironment('FLAVOR'),
      );

  /// Supabase API URL
  static const supabaseUrl = String.fromEnvironment('SUPABASE_URL');

  /// Supabase API key
  static const supabaseAnonKey = String.fromEnvironment('SUPABASE_ANON_KEY');

}

/// The flavors supported by the application
enum Flavor {
  /// The production flavor
  production,
  
  /// The staging flavor
  staging,
  
  /// The development flavor
  development,
  
}

extension FlavorExtension on Flavor {
  static Flavor fromString(String value) {
    switch (value) {
      case 'production':
        return Flavor.production;
      case 'staging':
        return Flavor.staging;
      case 'development':
        return Flavor.development;
      default:
        throw throw Exception('Invalid flavor');
    }
  }
}

    