// This file was generated by package:dart_define, DO NOT modify or remove these comments
class DartDefine {
  DartDefine._();
  
  /// The flavor the app was launched with
  static Flavor get flavor => FlavorExtension.fromString(
        const String.fromEnvironment('FLAVOR'),
      );

  /// Supabase API URL
  static const supabaseUrl = String.fromEnvironment('SUPABASE_URL');

  /// Supabase API key
  static const supabaseAnonKey = String.fromEnvironment('SUPABASE_ANON_KEY');

  /// Google OAuth web client ID
  static const googleOauthWebClientId = String.fromEnvironment('GOOGLE_OAUTH_WEB_CLIENT_ID');

  /// Google OAuth iOS client ID
  static const googleOauthIosClientId = String.fromEnvironment('GOOGLE_OAUTH_IOS_CLIENT_ID');

  /// Google API key for Android
  static const androidGoogleApiKey = String.fromEnvironment('ANDROID_GOOGLE_API_KEY');

  /// Goong API key
  static const goongApiKey = String.fromEnvironment('GOONG_API_KEY');

}

/// The flavors supported by the application
enum Flavor {
  /// The production flavor
  production,
  
  /// The staging flavor
  staging,
  
  /// The development flavor
  development,
  
}

extension FlavorExtension on Flavor {
  static Flavor fromString(String value) {
    switch (value) {
      case 'production':
        return Flavor.production;
      case 'staging':
        return Flavor.staging;
      case 'development':
        return Flavor.development;
      default:
        throw throw Exception('Invalid flavor');
    }
  }
}

    